### ISSUE TITLE
Feedback requisition notifications

### ISSUE THREAD

**Issue by MillerAdulu** [droidconKE/flutterconKEApp#107]
**Background**
To help with actively collecting feedback from sessions, we need to add a feature where after a session is over, event attendees can be asked to give feedback about their sessions. Already we have a feedback flow setup, so this would merely be a notification that once clicked, would allow a user to open the app and leave feedback. Since many sessions happen at the same time, this can be scoped to sessions that they bookmarked to attend. 

**Technial Implementation**
- Introduce the `awesome_notifications` package (pub.dev/packages/awesome_notifications). Ideally to remove the complexity around platform requirements for notifications
- Taking advantage of the notification scheduling feature (https://pub.dev/packages/awesome_notifications#-scheduling-a-notification), once a user is done bookmarking a session, the notification can be scheduled to display a few minutes before the session ends so that users who have bookmarked a session, are able to give feedback on it.

**Comment by NewtonMutugi** [comment]
I can take this up

**Comment by MillerAdulu** [comment]
@NewtonMutugi,

Once you have had a look and tried out a few things, please share a time estimate so that I can know when to expect to do a review.

**Comment by NewtonMutugi** [comment]
I believe I should be done by EOD
