### ISSUE TITLE
Homepage Search

### ISSUE THREAD

**Issue by MillerAdulu** [droidconKE/flutterconKEApp#126]
Hi @MillerAdulu ,
I had this UI sketch idea on Homepage first.
My time is a bit tight but you can create the issue and see how  well we can implement this.
Attached here is the suggested visual.(Subject to criticism and improvement)
![Screenshot 2024-09-05 at 16 01 53](https://github.com/user-attachments/assets/5c97c595-a82a-490a-9a04-d3af86834d44)

![Screenshot 2024-09-05 at 15 58 19](https://github.com/user-attachments/assets/2b3b3a43-3ae1-4d4a-98b4-fc84d95040d9)

_Originally posted by @NdegwaJulius in https://github.com/droidconKE/flutterconKEApp/discussions/124#discussioncomment-10557558_

**Comment by AlienDarkCat** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by MillerAdulu** [comment]
@NdegwaJulius, once you can get the UI working and open a Draft PR, we can work out how to implement the search from the local database

**Comment by chotixity** [comment]
you can break it down to
1. get the sessions persisted to local db
2. search feature
 this can help the issue get resolved a bit faster
