### ISSUE TITLE
Consuming APIs

### ISSUE THREAD

**Issue by SiroDaves** [droidconKE/flutterconKEApp#35]
Once Auth has been done, consuming the APIs should be easy. Optionally you can obtain the bearer token and be working on this issue.

**Comment by MillerAdulu** [comment]
Broken down into:
- https://github.com/droidconKE/flutterconKEApp/issues/48
- https://github.com/droidconKE/flutterconKEApp/issues/47
- https://github.com/droidconKE/flutterconKEApp/issues/46
- https://github.com/droidconKE/flutterconKEApp/issues/45
- https://github.com/droidconKE/flutterconKEApp/issues/44
