### ISSUE TITLE
Load feed

### ISSUE THREAD

**Issue by MillerAdulu** [droidconKE/flutterconKEApp#48]
We need to load the sessions into the app. 

API Path: `events/droidconke-2022-281/feeds`

Design Reference: https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/aabbe326-f4d9-4fae-9cbc-433491567613

Steps
Similar to the guidelines from https://github.com/droidconKE/flutterconKEApp/issues/44

Notes
- If you run into any problem, you can add a comment to this issue to have it resolved

**Comment by DevshiDeno** [comment]
Hello, is it okay if I started working on this issue.

**Comment by MillerAdulu** [comment]
Sure @DevshiDeno

**Comment by MillerAdulu** [comment]
@DevshiDeno,

Might you have a time estimate for this?

**Comment by DevshiDeno** [comment]
I've been going through issue when trying to run the project for debugging purposes, i'll paste it here for assistance.

**Comment by DevshiDeno** [comment]
Hello, I'll try and finish the task by the end of this week.
