### ISSUE TITLE
Share app posts to social media sites

### ISSUE THREAD

**Issue by MillerAdulu** [droidconKE/flutterconKEApp#61]
Design Ref: 
- https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/f5f3abf2-9384-460a-bac7-544c49648c0c/specs/
- https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/09ac0874-4933-4982-9e2e-b5d2c82d6c5f/specs/

A user should be allowed to share the content from the feed to social media sites.

**Initial Approach**
- Add `share_plus` (https://pub.dev/packages/share_plus)
- Ensure the content makes it over to the plugin for posting on the socials

**Edit**
Looks like we may need `appinio_social_share` (https://pub.dev/packages/appinio_social_share) to really achieve the social media effect

**Comment by MillerAdulu** [comment]
Looks like we may need `appinio_social_share` (https://pub.dev/packages/appinio_social_share) to really achieve the social media effect

**Comment by DanroyMwangi** [comment]
Hey, has this issue been resolved?

**Comment by MillerAdulu** [comment]
@DanroyMwangi,

This is partially resolved. Currently, you can do a share using the normal interface on the screen. What's now left is to add this section of the design linked to the issue. 

<img width="534" alt="Screenshot 2024-08-16 at 15 46 46" src="https://github.com/user-attachments/assets/3705f190-c84c-4f57-b818-86308cbf41f5">

As such, we need to implement this part
<img width="548" alt="Screenshot 2024-08-16 at 15 47 28" src="https://github.com/user-attachments/assets/d3e17fb2-790e-494d-8711-893f10b705c4">

If you would like to take this up, I can assign it to you.

**Comment by DanroyMwangi** [comment]
Could you please provide more details on the social media effect mentioned in the thread? Additionally, is the decision to use `appinio_social_share` finalized? I have an alternative suggestion: the `url_launcher` package (https://pub.dev/packages/url_launcher).

**Comment by MillerAdulu** [comment]
@DanroyMwangi,

The suggested approach one would take is:
- We have the `wolt_modal_sheet` as part of the code, so in `lib/features/feed/ui/feed_screen.dart`, you would adjust the code to launch the modal sheet (Sample of that in `lib/common/widgets/app_bar/app_bar.dart:74`
- You would then construct the UI on the modal that opens to showcase the buttons
- Then for each social media entry, you can use `appinio_social_share` (We have `lib/features/feed/cubit/share_feed_post_cubit.dart` that shows how to go about the sharing process that involves downloading the image if a post has one.

**Comment by MillerAdulu** [comment]
> Could you please provide more details on the social media effect mentioned in the thread? Additionally, is the decision to use `appinio_social_share` finalized? I have an alternative suggestion: the `url_launcher` package (https://pub.dev/packages/url_launcher).

This might prove challenging because `url_launcher` would launch the social media platform only and there's no way to share the file to a social media platform. So the post on the feed, should be shareable as a post that a person can post as themselves on their social media profile.

**Comment by MillerAdulu** [comment]
As an example of this, try and share an image from your WhatsApp DM to something like Twitter and Facebook. We should be able to achieve a similar effect.

**Comment by MillerAdulu** [comment]
If you can achieve the same effect with URL Launcher, I would be open to seeing your approach then we can finalise at the PR review. After all, there should be no qualms if it works.

**Comment by DanroyMwangi** [comment]
Thank you for the clear explanation. I’ll address the issue and submit a PR shortly. Could you please assign it to me?

**Comment by MillerAdulu** [comment]
@DanroyMwangi,

Kindly note the linked issue #88
