### ISSUE TITLE
Give feedback

### ISSUE THREAD

**Issue by MillerAdulu** [droidconKE/flutterconKEApp#67]
Setup a way for event-goers to give feedback across sessions. 

UI Ref: 
- https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/c87e6ded-5f2e-4f62-81f1-3940e677d79f/specs/
- https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/1ef2f9cd-d83b-4618-8f29-655f3a9483ae/specs/
- https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/1de29b30-29d7-4847-9a5d-90a60ff44249/specs/

APIs
- https://documenter.getpostman.com/view/3385291/SzS4TTXb#89b86d74-edc8-45e5-a778-fc4f4cb07d03
- https://documenter.getpostman.com/view/3385291/SzS4TTXb#dc20b345-95b6-46e1-929b-3df8ed5c4f51

**Comment by MillerAdulu** [comment]
@NewtonMutugi 

Do you think you can take on this particular issue?

**Comment by NewtonMutugi** [comment]
Yes I can take up this issue
