### ISSUE TITLE
Add a bit more documentation

### ISSUE THREAD

**Issue by mboyamike** [droidconKE/flutterconKEApp#7]
On the README, we should add some documentation 

I think this should involve the things like all the features the app should have, the file structure, apis/backend, theming, routing, state management, and any others

Perhaps we should also have a contributing.md file

**Comment by chepsi** [comment]
can I assign this to you @mboyamike ?

**Comment by mboyamike** [comment]
> can I assign this to you @mboyamike ?

Yeah, I'd be glad to do so
