### ISSUE TITLE
Update application assets

### ISSUE THREAD

**Issue by NewtonMutugi** [droidconKE/flutterconKEApp#83]
Update the application's assets to FlutterConKe instead of the current DroidConKe

**Comment by MillerAdulu** [comment]
@NewtonMutugi,

If you could expand on this a bit more. Do you have a list of all the pages where these changes need to happen? In addition, do you have the design reference that can be shared so that we are aligned on the source of the assets?

**Comment by NewtonMutugi** [comment]
The sections I am updating are:
- Appbar
- Home screen banner
- Launcher icon.
- Splashscreen

I believe this will be sufficient for a start.. However I can liase with the DroidConKe design team to for any more assets or design references that may be required.

https://drive.google.com/drive/folders/1RNgqdcrmwJ4CeRF_2F0IfR7Y_hYb3irC?usp=sharing
