### ISSUE TITLE
Weird loading on `Share`

### ISSUE THREAD

**Issue by root458** [droidconKE/flutterconKEApp#88]
As can be observed, when I click the Share button. All the posts are loading. This is quite confusing.

<img src="https://github.com/user-attachments/assets/44736768-6608-4b71-922c-85fdd9c3e1c7" width="300" >
<img src="https://github.com/user-attachments/assets/2ed70504-51ed-4a8b-9e67-d6fb15913bee" width="300" >

**Comment by MillerAdulu** [comment]
@DanroyMwangi,

As you work on #61, kindly address this issue. A similar feature is implemented in `lib/features/sessions/cubit/bookmark_session_cubit.dart`. When you click the button to share, pass in the index of that item in the list. Then in `lib/features/sessions/ui/widgets/compact_view_card.dart:116`, you check that the index matches to only show the spinner on only the post being shared.

**Comment by MillerAdulu** [comment]
Closed by #93
