### ISSUE TITLE
Light theme & dark theme

### ISSUE THREAD

**Issue by root458** [droidconKE/flutterconKEApp#90]
The app lacks a means to switch between light and dark themes.

This feature should be available as per the following designs: 
Light Theme: https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/ 
Dark Theme: https://xd.adobe.com/view/5ec235b6-c3c6-49a9-b783-1f1303deb1a8-0b91/

**Comment by MillerAdulu** [comment]
@root458,

While there's no button, the assumption is that the device is in dark mode so it picks it up automatically. Currently, to achieve feature completion, light mode was enforced. If you can take up this issue, I can assign it to you and we can discuss the approach cause the ground work for this already exists in the codebase.

**Comment by root458** [comment]
@MillerAdulu 

Nice. I'd gladly take this up. We can proceed to discuss the implementation. I will take some time to look at the codebase so that I get familiar and have a basis when having the discussion.

**Comment by MillerAdulu** [comment]
Concerning the approach:

- We have the theme file available at: `lib/core/theme/theme_data.dart`. It defines the dark and light themes. 
- To test that the theme looks OK on both light and dark mode, we have a function `lib/app.dart:28` which calls the Hive database `lib/common/repository/hive_repository.dart:58` and you can specify the mode you want then test the changes as you go along. 
- From there, it should be pretty standard, to switch the color in the UI based on the theme. For instance, `lib/common/widgets/app_bar/feedback_button.dart:34-36`

cc @root458

**Comment by root458** [comment]
Got it.

I will look into that and reach out for clarity on any issues I will have.

@MillerAdulu

**Comment by MillerAdulu** [comment]
@root458, 

As a follow-up comment. To help prevent unpleasant pull requests, what you can do is have the About page in dark mode first. Then open a draft PR at that point. We can harmonize on the code placement then you can love quickly through the other screens. That way there's less code review feedback.

**Comment by root458** [comment]
@MillerAdulu Got it. Great idea
