### ISSUE TITLE
Change app labels

### ISSUE THREAD

**Issue by MillerAdulu** [droidconKE/flutterconKEApp#98]
Change only the labels in the following places: 
- android/app/build.gradle:84,89,94
- ios/Runner.xcodeproj/project.pbxproj:542,637,727,822,915,1007,1102,1197,1287

That should be sufficient and should only take a couple of seconds.

_Originally posted by @MillerAdulu in https://github.com/droidconKE/flutterconKEApp/pull/97#discussion_r1721045120_

**Comment by NewtonMutugi** [comment]
On it
